// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: auth/login/oauth/v1/oauth_login.proto

package oauthloginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OAuthLoginService_Login_FullMethodName = "/auth.login.oauth.v1.OAuthLoginService/Login"
)

// OAuthLoginServiceClient is the client API for OAuthLoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthLoginServiceClient interface {
	// Login a user with OAuth provider
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type oAuthLoginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthLoginServiceClient(cc grpc.ClientConnInterface) OAuthLoginServiceClient {
	return &oAuthLoginServiceClient{cc}
}

func (c *oAuthLoginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, OAuthLoginService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthLoginServiceServer is the server API for OAuthLoginService service.
// All implementations must embed UnimplementedOAuthLoginServiceServer
// for forward compatibility.
type OAuthLoginServiceServer interface {
	// Login a user with OAuth provider
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedOAuthLoginServiceServer()
}

// UnimplementedOAuthLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthLoginServiceServer struct{}

func (UnimplementedOAuthLoginServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedOAuthLoginServiceServer) mustEmbedUnimplementedOAuthLoginServiceServer() {}
func (UnimplementedOAuthLoginServiceServer) testEmbeddedByValue()                           {}

// UnsafeOAuthLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthLoginServiceServer will
// result in compilation errors.
type UnsafeOAuthLoginServiceServer interface {
	mustEmbedUnimplementedOAuthLoginServiceServer()
}

func RegisterOAuthLoginServiceServer(s grpc.ServiceRegistrar, srv OAuthLoginServiceServer) {
	// If the following call pancis, it indicates UnimplementedOAuthLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthLoginService_ServiceDesc, srv)
}

func _OAuthLoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthLoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthLoginService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthLoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthLoginService_ServiceDesc is the grpc.ServiceDesc for OAuthLoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthLoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.login.oauth.v1.OAuthLoginService",
	HandlerType: (*OAuthLoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _OAuthLoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/login/oauth/v1/oauth_login.proto",
}
