// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"mandacode.com/accounts/auth/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"mandacode.com/accounts/auth/ent/authaccount"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AuthAccount is the client for interacting with the AuthAccount builders.
	AuthAccount *AuthAccountClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AuthAccount = NewAuthAccountClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		AuthAccount: NewAuthAccountClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		AuthAccount: NewAuthAccountClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AuthAccount.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AuthAccount.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AuthAccount.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AuthAccountMutation:
		return c.AuthAccount.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AuthAccountClient is a client for the AuthAccount schema.
type AuthAccountClient struct {
	config
}

// NewAuthAccountClient returns a client for the AuthAccount from the given config.
func NewAuthAccountClient(c config) *AuthAccountClient {
	return &AuthAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `authaccount.Hooks(f(g(h())))`.
func (c *AuthAccountClient) Use(hooks ...Hook) {
	c.hooks.AuthAccount = append(c.hooks.AuthAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `authaccount.Intercept(f(g(h())))`.
func (c *AuthAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuthAccount = append(c.inters.AuthAccount, interceptors...)
}

// Create returns a builder for creating a AuthAccount entity.
func (c *AuthAccountClient) Create() *AuthAccountCreate {
	mutation := newAuthAccountMutation(c.config, OpCreate)
	return &AuthAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuthAccount entities.
func (c *AuthAccountClient) CreateBulk(builders ...*AuthAccountCreate) *AuthAccountCreateBulk {
	return &AuthAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuthAccountClient) MapCreateBulk(slice any, setFunc func(*AuthAccountCreate, int)) *AuthAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuthAccountCreateBulk{err: fmt.Errorf("calling to AuthAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuthAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuthAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuthAccount.
func (c *AuthAccountClient) Update() *AuthAccountUpdate {
	mutation := newAuthAccountMutation(c.config, OpUpdate)
	return &AuthAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuthAccountClient) UpdateOne(aa *AuthAccount) *AuthAccountUpdateOne {
	mutation := newAuthAccountMutation(c.config, OpUpdateOne, withAuthAccount(aa))
	return &AuthAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuthAccountClient) UpdateOneID(id uuid.UUID) *AuthAccountUpdateOne {
	mutation := newAuthAccountMutation(c.config, OpUpdateOne, withAuthAccountID(id))
	return &AuthAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuthAccount.
func (c *AuthAccountClient) Delete() *AuthAccountDelete {
	mutation := newAuthAccountMutation(c.config, OpDelete)
	return &AuthAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuthAccountClient) DeleteOne(aa *AuthAccount) *AuthAccountDeleteOne {
	return c.DeleteOneID(aa.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuthAccountClient) DeleteOneID(id uuid.UUID) *AuthAccountDeleteOne {
	builder := c.Delete().Where(authaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuthAccountDeleteOne{builder}
}

// Query returns a query builder for AuthAccount.
func (c *AuthAccountClient) Query() *AuthAccountQuery {
	return &AuthAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuthAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a AuthAccount entity by its id.
func (c *AuthAccountClient) Get(ctx context.Context, id uuid.UUID) (*AuthAccount, error) {
	return c.Query().Where(authaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuthAccountClient) GetX(ctx context.Context, id uuid.UUID) *AuthAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuthAccountClient) Hooks() []Hook {
	hooks := c.hooks.AuthAccount
	return append(hooks[:len(hooks):len(hooks)], authaccount.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *AuthAccountClient) Interceptors() []Interceptor {
	return c.inters.AuthAccount
}

func (c *AuthAccountClient) mutate(ctx context.Context, m *AuthAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuthAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuthAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuthAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuthAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuthAccount mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AuthAccount []ent.Hook
	}
	inters struct {
		AuthAccount []ent.Interceptor
	}
)
