// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/google/uuid"
	"mandacode.com/accounts/auth/ent/authaccount"
	"mandacode.com/accounts/auth/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authaccountHooks := schema.AuthAccount{}.Hooks()
	authaccount.Hooks[0] = authaccountHooks[0]
	authaccount.Hooks[1] = authaccountHooks[1]
	authaccountFields := schema.AuthAccount{}.Fields()
	_ = authaccountFields
	// authaccountDescIsVerified is the schema descriptor for is_verified field.
	authaccountDescIsVerified := authaccountFields[4].Descriptor()
	// authaccount.DefaultIsVerified holds the default value on creation for the is_verified field.
	authaccount.DefaultIsVerified = authaccountDescIsVerified.Default.(bool)
	// authaccountDescEmail is the schema descriptor for email field.
	authaccountDescEmail := authaccountFields[5].Descriptor()
	// authaccount.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	authaccount.EmailValidator = authaccountDescEmail.Validators[0].(func(string) error)
	// authaccountDescCreatedAt is the schema descriptor for created_at field.
	authaccountDescCreatedAt := authaccountFields[7].Descriptor()
	// authaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	authaccount.DefaultCreatedAt = authaccountDescCreatedAt.Default.(func() time.Time)
	// authaccountDescUpdatedAt is the schema descriptor for updated_at field.
	authaccountDescUpdatedAt := authaccountFields[8].Descriptor()
	// authaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authaccount.DefaultUpdatedAt = authaccountDescUpdatedAt.Default.(func() time.Time)
	// authaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authaccount.UpdateDefaultUpdatedAt = authaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authaccountDescID is the schema descriptor for id field.
	authaccountDescID := authaccountFields[0].Descriptor()
	// authaccount.DefaultID holds the default value on creation for the id field.
	authaccount.DefaultID = authaccountDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.4"                                         // Version of ent codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent codegen.
)
