// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LocalUsersColumns holds the columns for the "local_users" table.
	LocalUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// LocalUsersTable holds the schema information for the "local_users" table.
	LocalUsersTable = &schema.Table{
		Name:       "local_users",
		Columns:    LocalUsersColumns,
		PrimaryKey: []*schema.Column{LocalUsersColumns[0]},
	}
	// OauthUsersColumns holds the columns for the "oauth_users" table.
	OauthUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"google", "github", "facebook", "kakao", "naver", "apple"}},
		{Name: "provider_id", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_verified", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthUsersTable holds the schema information for the "oauth_users" table.
	OauthUsersTable = &schema.Table{
		Name:       "oauth_users",
		Columns:    OauthUsersColumns,
		PrimaryKey: []*schema.Column{OauthUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthuser_id_provider",
				Unique:  true,
				Columns: []*schema.Column{OauthUsersColumns[0], OauthUsersColumns[2]},
			},
			{
				Name:    "oauthuser_provider_provider_id",
				Unique:  true,
				Columns: []*schema.Column{OauthUsersColumns[2], OauthUsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LocalUsersTable,
		OauthUsersTable,
	}
)

func init() {
}
